# Generated by Django 3.1.7 on 2022-04-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.TextField()),
                ('nationality', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
