# Generated by Django 3.1.7 on 2022-04-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='athletes',
            name='weight',
            field=models.CharField(max_length=100),
        ),
    ]
