# Generated by Django 3.1.7 on 2022-04-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_athletes_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='age',
            field=models.IntegerField(null='00'),
        ),
    ]
