# Generated by Django 3.1.7 on 2022-04-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20220429_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='age',
            field=models.IntegerField(default=00, null=''),
            preserve_default=False,
        ),
    ]
